name: Qt-CI

on:
  push:
    branches: [ "ci-cd" ]
  pull_request:
    branches: [ "main" ]

env:
  ARTIFACT: QtCiCd

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.*'
          cache: 'false'
          install-deps: 'true'
          setup-python: 'false'
          modules: 'qtwebsockets'

      - name: Install Ninja
        run: sudo apt install ninja-build cmake -y

      - name: create a .env file
        run: rm -f .env && touch .env && echo "SECRET_KEY=${{secrets.UBUNTO_BUILD_SECRET}}" > ./.env

      - name: configure project using qt-cmake
        run: ${{env.QT_ROOT_DIR}}/bin/qt-cmake . -B build

      - name: build the configuration using cmake
        run: |
          cd build
          cmake --build . --parallel 4
        
      - name: pack the bundle
        run: cd ${{github.workspace}}/build && cpack -B ../pack -G TGZ
          
      - name: Save build and report files
        uses: actions/upload-artifact@v4.3.1
        with:
          name: 'pack'
          path: ${{github.workspace}}/pack/InLink-0.1-Linux.tar.gz
