name: Qt-CI

on:
  push:
    branches: [ "ci-cd" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  ARTIFACT: QtCiCd

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.*'
          cache: 'false'
          install-deps: 'true'
          setup-python: 'false'
          modules: 'qtwebsockets'

      - name: List and find the Qt-Cmake Executable
        run: ls -ls ${{env.QT_ROOT_DIR}}/bin | grep -E '(qt-cmake|lupdate|lrelease|lconvert)' -

      - name: Install Ninja
        run: sudo apt install ninja-build -y

      - name: create a .env file
        run: rm .env && touch .env && echo "SECRET_KEY=${{secrets.UBUNTO_BUILD_SECRET}}" > ./.env

      - name: Run Qt-Cmake for building the project
        run: |
          ${{env.QT_ROOT_DIR}}/bin/qt-cmake . -B build
          cd build && ${{env.QT_ROOT_DIR}}/bin/qt-cmake --build . --parallel 4
          
      # - name: Save build and report files
      #   uses: actions/upload-artifact@v4.3.1
      #   with:
      #     name: 'build'
      #     path: |
      #         ${{github.workspace}}/build
